apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-movie-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.movie_service.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:  
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:  
      containers:
        - name: movie_service
          image: {{ .Values.movie_service.image }}
          ports:
            - containerPort: {{ .Values.movie_service.service.port }}
          volumeMounts: 
          - name: volume-movie
            mountPath: /app
          env:
          - name: DATABASE_URI
            value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
          - name: CAST_SERVICE_HOST_URL
            value: http://cast_service:8000/api/v1/casts/
      volumes:
      - name: volume-movie


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-cast-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.cast_service.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:  
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:  
      containers:
        - name: cast_service
          image: {{ .Values.cast_service.image }}
          ports:
            - containerPort: {{ .Values.cast_service.service.port }}
          volumeMounts: 
          - name: volume-cast
            mountPath: /app
          env:
          - name: DATABASE_URI
            value: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
      volumes:
      - name: volume-cast

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-nginx
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:  
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:  
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          volumeMounts: 
          - name: volume-nginx
            mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: volume-nginx
