apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}-movie
  namespace : {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}-cast
  namespace : {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage}}
