apiVersion: v1
kind: Secret
metadata:
  name: movie
  namespace : {{ .Values.namespace }}
type: Opaque
data:
    postgres-user: bW92aWVfZGJfdXNlcm5hbWUK
    postgres-password: bW92aWVfZGJfcGFzc3dvcmQK
    postgres-db: bW92aWVfZGJfZGV2Cg==

---
apiVersion: v1
kind: Secret
metadata:
  name: cast
  namespace : {{ .Values.namespace }}
type: Opaque
data:
    postgres-user: Y2FzdF9kYl91c2VybmFtZQo=
    postgres-password: Y2FzdF9kYl9wYXNzd29yZAo=
    postgres-db: Y2FzdF9kYl9kZXYK