apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: {{ include "helm.fullname" . }}-movie-db
 namespace : {{ .Values.namespace }}
spec:
 selector:
   matchLabels:
     {{- include "helm.selectorLabels" . | nindent 6 }}
 replicas: {{ .Values.movie_db.replicaCount }}
 template:
   metadata:
     labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
   spec:
     containers:
     - name: movie-db
       image: {{ .Values.movie_db.image }}
       ports:
       - containerPort: {{ .Values.movie_db.service.port }}
       volumeMounts:
       - name: {{ .Values.pvc.name }}-movie
         mountPath: /var/lib/postgresql/data
         subPath: postgres
       env:
       - name: POSTGRES_USER
         valueFrom:
           secretKeyRef:
             name: movie
             key: postgres-user
       - name: POSTGRES_PASSWORD
         valueFrom:
           secretKeyRef:
             name: movie
             key: postgres-password
       - name: POSTGRES_DB
         valueFrom:
          secretKeyRef:
             name: movie
             key: postgres-db
     volumes:
      - name: {{ .Values.pvc.name }}-movie
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}-movie

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: {{ include "helm.fullname" . }}-cast-db
 namespace : {{ .Values.namespace }}
spec:
 selector:
   matchLabels:
     {{- include "helm.selectorLabels" . | nindent 6 }}
 replicas: {{ .Values.cast_db.replicaCount }}
 template:
   metadata:
     labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
   spec:
     containers:
     - name: movie-db
       image: {{ .Values.cast_db.image }}
       ports:
       - containerPort: {{ .Values.cast_db.service.port }}
       volumeMounts:
       - name: {{ .Values.pvc.name }}-cast
         mountPath: /var/lib/postgresql/data
         subPath: postgres
       env:
       - name: POSTGRES_USER
         valueFrom:
           secretKeyRef:
             name: cast
             key: postgres-user
       - name: POSTGRES_PASSWORD
         valueFrom:
           secretKeyRef:
             name: cast
             key: postgres-password
       - name: POSTGRES_DB
         valueFrom:
          secretKeyRef:
             name: cast
             key: postgres-db
     volumes:
      - name: {{ .Values.pvc.name }}-cast
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}-cast